routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', function(){ return view('layouts.login'); })->name('login');
Route::get('/dashboard', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);
Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);

Route::prefix('kpi')->name('kpi.')->group(function () {
    Route::get('/laporan-pantauan', ['uses' => 'KpiController@pantauan', 'as' => 'pemantauan']);
    Route::get('/laporan-pantauan/print', ['uses' => 'KpiController@downloadPDF', 'as' => 'print']);
    Route::get('/penyelarasan', ['uses' => 'KpiController@penyelarasan', 'as' => 'penyelarasan']);
    Route::get('/penyerahan', ['uses' => 'KpiController@penyerahan', 'as' => 'penyerahan']);
    Route::get('/edit', ['uses' => 'KpiController@edit', 'as' => 'edit']);
    Route::get('/senarai', ['uses' => 'KpiController@senarai', 'as' => 'senarai']);
});

Route::prefix('ketua-jabatan')->name('ketua-jabatan.')->group(function () {
    Route::get('/dashboard', ['uses' => 'KetuaJabatanController@index', 'as' => 'dashboard']);
    Route::get('/penyelarasan', ['uses' => 'KetuaJabatanController@penyelarasan', 'as' => 'penyelarasan']);
});

Route::prefix('penyelaras')->name('penyelaras.')->group(function () {
    Route::get('/dashboard', ['uses' => 'PenyelarasController@index', 'as' => 'dashboard']);
    Route::get('/penyelarasan', ['uses' => 'PenyelarasController@penyelarasan', 'as' => 'penyelarasan']);
});

Route::prefix('pelulus')->name('pelulus.')->group(function () {
    Route::get('/dashboard', ['uses' => 'PelulusController@index', 'as' => 'dashboard']);
    Route::get('/penyerahan', ['uses' => 'PelulusController@penyerahan', 'as' => 'penyerahan']);
    Route::get('/senarai', ['uses' => 'PelulusController@senarai', 'as' => 'senarai']);
});

resources/views/modal/edit-kpi.blade.php
<!-- Modal -->
<div class="modal fade" id="laporanKpiModal" tabindex="-1" role="dialog" aria-labelledby="laporanKpiModalTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered modal-a4" role="document">
    <div class="modal-content">
    <div class="modal-body">
        <div class="container-fluid">
            <div class="row mb-3">
                <div class="col-12">
                    <div>Edit:</div>
                    <div>Inisiatif 1-1: Mesyuarat/Perbincangan Awal</div>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        <label>Inisiatif</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-group custom-group">
                        <label>Sasaran</label>
                        <span><img src="../img/info.svg" alt=""></span>
                        <div>
                            <input type="text" class="form-control">
                            <input type="text" class="form-control">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <div class="form-group custom-group">
                        <label>Pencapaian</label>
                        <span><img src="../img/info.svg" alt=""></span>
                        <div>
                            <select type="text" class="form-control">
                                <option value="Selesai">Selesai</option>
                            </select>
                            <input type="text" class="form-control">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Kemajuan</label>
                        <span><img src="../img/info.svg" alt=""></span>
                        <input type="text" class="form-control">
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label>Pemberat</label>
                        <input type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Catatan</label>
                        <textarea class="form-control" rows="7"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" type="button" data-dismiss="modal">
            <span><img class="btn-icon" src="../img/kembali-white.svg" alt=""></span>
            Kembali
        </button>
        <button class="btn btn-primary" type="button" data-dismiss="modal">
            <span><img class="btn-icon" src="../img/save-white.svg" alt=""></span>
            Simpan
        </button>
    </div>
    </div>
</div>
</div>

resources/views/modal/kembali.blade.php
<div class="modal fade" id="backModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <div class="p-5">
                    <div class="mb-3">KPI Kumpulan Pembangunan Berjaya Diserahkan untuk tindakan Unit Korporat & Kualiti</div>
                    
                    <button class="btn btn-primary" type="button" data-dismiss="modal">
                        <span><img class="btn-icon" src="../img/kembali-white.svg" alt=""></span>
                        Kembali
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/modal/komen.blade.php
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="pb-2">
                    <div>Komen untuk:</div>
                    <div>Bahagian Khidmat Pengurusan</div>
                </div>
                <div>Catatan</div>
                <div class="text-container">
                    <textarea class="form-control" rows="10"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" type="button" data-dismiss="modal">
                    <span><img class="btn-icon" src="../img/kembali-white.svg" alt=""></span>
                    Kembali
                </button>
                <button class="btn btn-primary" type="button" data-dismiss="modal" data-toggle="modal" data-target="#saveModal">
                    <span><img class="btn-icon" src="../img/save-white.svg" alt=""></span>
                    Simpan
                </button>
            </div>
        </div>
    </div>
</div>

resources/views/modal/laporan-kpi-content.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="../../css/app.css" />
</head>
<body>
    <div class="container-fluid laporan">
        <div class="row modal-title">
            <div class="col text-center">
                <span class="nama">
                    Laporan Key Performance Indicator (KPI) 2018 <br>
                    Q1 (Januari - Mac)
                </span> 
            </div>
        </div>
        <hr>
        <div class="row modal-graph">
            <div class="col text-center">
                <i>GRAPH HERE</i>
            </div>
        </div>
        <hr>
        <div class="row text-center mb-5">
            <div class="col-12 mb-3">
                <img src="../img/upen.png" class="logo" alt="">
            </div>
            <div class="col-12">
                <span class="nama">Badan Kawal Selia Air Johor (BAKAJ)</span>
            </div>
        </div>
        <div class="row text-center mb-3 traffic">
            <div class="col-4 col-md-2 traffic-title">
                <div class="num">20</div>
                <div class="desc">KPI</div>
            </div>
            <div class="col-4 col-md-2 traffic-light">
                <div class="green">
                    <div class="num">20</div>
                </div>
                <span class="small">85% ke atas</span>
            </div>
            <div class="col-4 col-md-2 traffic-light">
                <div class="orange">
                    <div class="num">20</div>
                </div>
                <span class="small">50% - 85%</span>
            </div>
            <div class="col-4 col-md-2 traffic-light">
                <div class="red">
                    <div class="num">20</div>
                </div>
                <span class="small">50% ke bawah</span>
            </div>
            <div class="col-4 col-md-2 traffic-light">
                <div class="blue">
                    <div class="num">20</div>
                </div>
                <span class="small">Tiada status</span>
            </div>
            <div class="col-4 col-md-2 traffic-light">
                <div class="grey">
                    <div class="num">20</div>
                </div>
                <span class="small">Gugur/Tidak aktif</span>
            </div>
        </div>
        <div class="row text-center mb-3 traffic">
            <div class="col-4 col-md-2 traffic-title">
                <div class="num">20</div>
                <div class="desc">KPI</div>
            </div>
            <div class="col-4 col-md-2 traffic-light">
                <div class="green">
                    <div class="num">20</div>
                </div>
                <span class="small">85% ke atas</span>
            </div>
            <div class="col-4 col-md-2 traffic-light">
                <div class="orange">
                    <div class="num">20</div>
                </div>
                <span class="small">50% - 85%</span>
            </div>
            <div class="col-4 col-md-2 traffic-light">
                <div class="red">
                    <div class="num">20</div>
                </div>
                <span class="small">50% ke bawah</span>
            </div>
            <div class="col-4 col-md-2 traffic-light">
                <div class="blue">
                    <div class="num">20</div>
                </div>
                <span class="small">Tiada status</span>
            </div>
            <div class="col-4 col-md-2 traffic-light">
                <div class="grey">
                    <div class="num">20</div>
                </div>
                <span class="small">Gugur/Tidak aktif</span>
            </div>
        </div>
        <hr>
        <div class="row modal-table">
            <div class="col-12 fokus">
                <span>FOKUS 1: Menyediakan kemudahan Awam dan Infrastruktur</span>
            </div>
            <div class="col-12 objektif">
                <span>Objektif 1: Mengurus Tadbir Urus Air</span>
            </div>
            <div class="col-2 kpi-title">
                <span>KPI</span>
            </div>
            <div class="col-10 kpi-description">
                <span>Jumlah Pembinaan Telaga Tiub</span>
                <div class="kpi-achievement">
                    50%
                </div>
            </div>
            <div class="col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Sasaran</th>
                            <th>Pencapaian</th>
                            <th>Catatan</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                2 buah telaga di Kota Tinggi
                            </td>
                            <td>
                                Dalam Penyediaan Kertas Kerja untuk dibawa kepada Jawatankuasa Rundingan Harga Peringkat Negeri
                            </td>
                            <td>
                                Sebagaimana Lampiran
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-12">
                <table class="table table-laporan">
                    <thead>
                        <tr class="text-center">
                            <th scope="col-2">Inisiatif</th>
                            <th scope="col-2">Sasaran 2018</th>
                            <th scope="col-3">Pencapaian Sehingga Disember 2017</th>
                            <th scope="col-2">Kemajuan</th>
                            <th scope="col-2">Catatan</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-center">
                                Inisiatif 1-1: <br>
                                Mesyuarat / Perbincangan Awal
                            </td>
                            <td class="text-center">
                                Jan 2017
                            </td>
                            <td>
                                Selesai mesyuarat diadakan pada 9.1.2017
                            </td>
                            <td class="text-center">
                                <div class="kemajuan green">100%</div>
                            </td>
                            <td>
                                Tiada catatan buat masa ini
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                Inisiatif 1-1: <br>
                                Mesyuarat / Perbincangan Awal
                            </td>
                            <td class="text-center">
                                Jan 2017
                            </td>
                            <td>
                                Selesai mesyuarat diadakan pada 9.1.2017
                            </td>
                            <td class="text-center">
                                <div class="kemajuan orange">70%</div>
                            </td>
                            <td>
                                Tiada catatan buat masa ini
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>    
</body>
</html>

resources/views/modal/laporan-kpi.blade.php
<!-- Modal -->
<div class="modal fade" id="laporanKpiModal" tabindex="-1" role="dialog" aria-labelledby="laporanKpiModalTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered modal-a4" role="document">
    <div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 text-right">
                <a href="{{ route('kpi.print') }}" class="btn btn-primary">Muat turun PDF</a>
                </div>
            </div>
        </div>
        @include('modal.laporan-kpi-content')
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
    </div>
    </div>
</div>
</div>

resources/views/modal/simpan.blade.php
<div class="modal fade" id="saveModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="p-4">
                    <div class="green-tick mb-3">
                        <span><img src="../img/check-white.svg" alt=""></span>
                    </div>
                    <div class="text-center">
                        <div class="mb-2">
                            Catatan Berjaya Disimpan
                        </div>
                        <button class="btn btn-primary" type="button" data-dismiss="modal">
                            {{-- <span><img class="btn-icon" src="../img/save-white.svg" alt=""></span> --}}
                            OK
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>