routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', function(){ return view('layouts.login'); })->name('login');
Route::get('/dashboard', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);
Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);

Route::prefix('kpi')->name('kpi.')->group(function () {
    Route::get('/laporan-pantauan', ['uses' => 'KpiController@pantauan', 'as' => 'pemantauan']);
    Route::get('/laporan-pantauan/print', ['uses' => 'KpiController@downloadPDF', 'as' => 'print']);
    Route::get('/penyelarasan', ['uses' => 'KpiController@penyelarasan', 'as' => 'penyelarasan']);
    Route::get('/penyerahan', ['uses' => 'KpiController@penyerahan', 'as' => 'penyerahan']);
    Route::get('/edit', ['uses' => 'KpiController@edit', 'as' => 'edit']);
    Route::get('/senarai', ['uses' => 'KpiController@senarai', 'as' => 'senarai']);
});

Route::prefix('ketua-jabatan')->name('ketua-jabatan.')->group(function () {
    Route::get('/dashboard', ['uses' => 'KetuaJabatanController@index', 'as' => 'dashboard']);
    Route::get('/penyelarasan', ['uses' => 'KetuaJabatanController@penyelarasan', 'as' => 'penyelarasan']);
});

Route::prefix('penyelaras')->name('penyelaras.')->group(function () {
    Route::get('/dashboard', ['uses' => 'PenyelarasController@index', 'as' => 'dashboard']);
    Route::get('/penyelarasan', ['uses' => 'PenyelarasController@penyelarasan', 'as' => 'penyelarasan']);
});

Route::prefix('pelulus')->name('pelulus.')->group(function () {
    Route::get('/dashboard', ['uses' => 'PelulusController@index', 'as' => 'dashboard']);
    Route::get('/penyerahan', ['uses' => 'PelulusController@penyerahan', 'as' => 'penyerahan']);
    Route::get('/senarai', ['uses' => 'PelulusController@senarai', 'as' => 'senarai']);
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>JIPS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="../css/app.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>
<body>
    @if(Request::path() !== 'login')
        @include('layouts.navbar')
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidenav">
                    @include('layouts.side-nav')
                </div>    
                <div class="col-12 col-sm content">
                    @yield('content')
                </div>
            </div>
        </div>
    @elseif(Request::path() === 'login')
        <div class="container-fluid">
            @yield('content')
        </div>
    @endif
    
    <script src="../js/app.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <script>
        $(window).scroll(function() {
            if ($(window).scrollTop() >= 100) {
                $('.sidenav > .row').css('padding-top', '30px');
            } else {
                $('.sidenav > .row').css('padding-top', '130px');
            }
        });
    </script>
</body>
</html>

resources/views/layouts/login.blade.php
@extends('layouts.app')

@section('content')
    <div class="row full-height login-page justify-content-md-center align-items-center">
        <div class="col-md-4 p-5 mr-sm-3 ml-sm-3 mt-sm-3 mb-sm-0 m-md-0 login-wrapper">
            <div class="text-center">
                <div class="login-instruction">
                    Sila masukkan ID pengguna anda beserta kata laluan anda
                </div>
                <div class="login-input">
                    <img src="../img/profile_round.svg" alt="">
                    <input type="text">
                </div>
                <div class="login-input mb-4">
                        <img src="../img/key_1.svg" alt="">
                    <input type="password">
                </div>
                <div class="login-btn mb-3">
                    <a class="btn btn-primary" href="{{ route('dashboard') }}">LOG MASUK</a>
                </div>
                <div class="mb-3">
                    <small>Terlupa kata laluan anda?</small>
                <small>Klik di <a href="#">sini</a></small>
                </div>
                <div class="row login-ict">
                    <div class="col-5 p-0">
                        <img src="../img/Logo BST ICT.png" alt="">
                    </div>
                    <div class="col-7 p-0">
                        <span>Di selenggara oleh:</span>
                        <br>
                        <span>Bahagian Sains Teknologi & ICT Johor</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 p-5 mr-sm-3 ml-sm-3 mb-sm-3 m-md-0 login-wrapper">
            <div class="login-logo">
                <img src="../img/JataJohor.svg" alt="">
            </div>
            <div class="login-description">
                <div class="title my-4">Johor Indeks Prestasi Sistem</div>
                <div class="description">Portal Johor Indeks Prestasi Sistem adalah bagi pemantauan KPI jabatan-jabatan kerajaan seluruh negeri Johor oleh pihak SUK</div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/navbar.blade.php
<div class="navigation">
    <nav class="navbar fixed-top">
        <div class="container-fluid nav-wrapper">
            <div class="row px-5 align-items-center">
                <div class="col-4">
                    <a class="navbar-brand" href="#">
                        <img src="../img/JataJohor.svg" alt="" style="width:80px">
                    </a>
                </div>
                <div class="col-8">
                    <span>Johor Indeks Prestasi Sistem</span>
                </div>
            </div>
        </div>
    </nav>
    <div style="margin-top: 42px !important"></div>
    <div class="container-fluid subnav">
        <div class="row py-3 px-4 align-items-center pegawai-kpi">
            <div class="col-3 col-sm col-md-1 text-right">
                <img src="../img/JataJohor.svg" alt="">
            </div>
            <div class="col-9 col-sm-5 pl-0">
                <span>Unit Korporat & Kualiti</span>
            </div>
            <div class="col-12 col-sm col-md-4 text-right px-0 d-none d-sm-block">
                <img class="avatar" src="../img/avatar.png" alt="">
            </div>
            <div class="col-6 col-sm col-md-1 name-info">
                <div class="name">Wahida Amalin</div>
                <div class="position">Pegawai KPI</div>
            </div>
            <div class="col-6 col-sm col-md-1 text-right">
                <a class="btn btn-primary btn-round" href="{{ route('login') }}">KELUAR</a>
            </div>
        </div>
    </div>
    <span class="clearfix"></span>
</div>

resources/views/layouts/side-nav.blade.php
<div class="row">
    <div class="col-12 selected">
        <a href="{{ route('dashboard') }}">
            <div class="text">dashboard</div>
            <img src="../img/dashboard-blue.svg" alt="">
        </a>
    </div>
    <div class="col-12">
        <a href="{{ route('kpi.senarai') }}">
            <div class="text">senarai kpi</div>
            <img src="../img/senarai-kpi-white.svg" alt="">
        </a>
    </div>
    <div class="col-12">
        <a href="{{ route('kpi.edit') }}">
            <div class="text">edit kpi</div>
            <img src="../img/edit-kpi-white.svg" alt="">
        </a>
    </div>
    <div class="col-12">
        <a href="{{ route('kpi.penyerahan') }}">
            <div class="text">serah kpi</div>
            <img src="../img/serah-kpi-white.svg" alt="">
        </a>
    </div>
    <div class="col-12">
        <div class="text">profil</div>
        <img src="../img/profile-white.svg" alt="">
    </div>
    <div class="col-12">
        <div class="text">tetapan</div>
        <img src="../img/setting-white.svg" alt="">
    </div>
</div>